langauge: ruby
sudo: enabled
before_install:
  sudo add-apt-repository ppa:chris-lea/libsodium -y;
  sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  sudo apt-get update && sudo apt-get install libsodium-dev;
install:
  bundle --path vendor
  bundle --binstubs
brefore_script:
  bin/rake sqlite:migrate
script: 
  bin/rspec --format doc
after_script:
  bin/rake sqlite:delete
rvm:
  - 2.4.1
